version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: db_snowflake
    restart: always
    environment:
      POSTGRES_DB: mockDB
      POSTGRES_USER: mocker
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./task:/docker-entrypoint-initdb.d

volumes:
  postgres_data: